security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            stateless: true
            provider: users
            jwt: ~

        main:
            lazy: true
            provider: users  # Đảm bảo bạn đang sử dụng đúng provider
            json_login:
                check_path: auth # The name in routes.yaml is enough for mapping
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure


    access_control:
#        - { path: ^/api/login, roles: PUBLIC_ACCESS }
#        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
